name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf .github
      - run: rm -rf .git
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "."
          destination-github-username: "mathieudutour"
          destination-repository-name: "iecmb-website"
          user-email: mathieu@dutour.me
